Repository innovateorange/DiscordBot, pull requests merged in 2025-07, with the labels that each got.

#67 Added removeDuplicates() & extract_entries_from_csv()
  data_collections/csv_updater.py
  data_collections/getEvents.py
  data_collections/runningCSV.csv
  tests/csv_updater_test.py
Labels: enhancement, Data Collections, mvp, python

#86 Hotfix/grammar issue in bot.py
  README.md
  bot.py
Labels: enhancement

#95 Updated events.py with missing column
  data_collections/README.md
  data_collections/events.py
  data_collections/mainRSSRunner.py
  data_collections/runningCSV.csv
Labels: documentation, enhancement, Data Collections, mvp, python

#96 Added Automatic deployments
  .github/workflows/prod-deploy.yml
  .github/workflows/staging-deploy.yml
Labels: mvp

#123 Spelling, grammar and type definition fixes
  bot.py
  data_collections/csv_updater.py
  data_processing/job_event.py
  tests/job_event_test.py
Labels: documentation, enhancement

#132 Added check-stage.yaml
  .github/workflows/check-stage.yaml
Labels: enhancement, mvp

#139 Release/v0.0.2
  CONTRIBUTING.md
Labels: documentation

#142 Feature/add new event feeds
  .github/workflows/rss-runner.yaml
  .gitignore
  data_collections/events.py
  data_collections/mainRSSRunner.py
  data_collections/runningCSV.csv
  tests/events_test.py
Labels: enhancement, Data Collections, python

#146 Feature/rss jobs internships
  .github/workflows/rss-runner.yaml
  data_collections/constants.py
  data_collections/csv_updater.py
  data_collections/mainRSSRunner.py
  data_collections/rss_parser.py
  tests/rss_parser_test.py
Labels: enhancement, Data Collections, mvp, python

#151 [Feature]: Update check-stage.yml w/ new logic
  .github/workflows/check-stage.yaml
Labels: enhancement
